apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aa-paymaster.fullname" . }}
  labels:
    {{- include "aa-paymaster.labels" . | nindent 4 }}
data:
  .env: |-
{{- range $key, $value := .Values.aa_paymaster.env }}
    {{ $key }}={{ $value }}
{{- end }}
