title: "[Feedback] <Title>"
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        # Feedback
        
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Please provide feedback on how we're doing.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please provide any additional relevant information i.e. documnetation links
