apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos-stack.fullname" . }}-common
  labels:
    {{- include "thanos-stack.labels" . | nindent 4 }}
data:
  L2_NODE_WEB3_URL: {{ .Values.common.l2_node_web3_url | default (printf "http://%s-op-geth:8545" (include "thanos-stack.fullname" .)) | quote }}
  L2_ROLLUP_WEB3_URL: {{ .Values.common.l2_rollup_web3_url | default (printf "http://%s-op-node:8545" (include "thanos-stack.fullname" .)) | quote }}
