apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-ext-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "thanos-stack.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: {{ include "thanos-stack.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: OP_NODE_P2P_SEQUENCER_KEY
      remoteRef:
        key: {{ .Values.thanos_stack_infra.name }}/secrets
        property: OP_NODE_P2P_SEQUENCER_KEY
    - secretKey: OP_BATCHER_PRIVATE_KEY
      remoteRef:
        key: {{ .Values.thanos_stack_infra.name }}/secrets
        property: OP_BATCHER_PRIVATE_KEY
    - secretKey: OP_PROPOSER_PRIVATE_KEY
      remoteRef:
        key: {{ .Values.thanos_stack_infra.name }}/secrets
        property: OP_PROPOSER_PRIVATE_KEY
    - secretKey: OP_CHALLENGER_PRIVATE_KEY
      remoteRef:
        key: {{ .Values.thanos_stack_infra.name }}/secrets
        property: OP_CHALLENGER_PRIVATE_KEY
