{{- if .Values.graph_node.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos-stack.fullname" . }}-graph-node
data:
{{- range $key, $value := .Values.graph_node.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  ethereum: {{ .Values.l2_rpc.node | default (printf "thanos-stack:http://%s-op-geth:8545" (include "thanos-stack.fullname" .)) | quote }}
  ipfs: {{ printf "%s-ipfs:5001" (include "thanos-stack.fullname" .) | quote }}
{{- end}}
