{{- if not .Values.createPvc }}
{{- if .Values.graph_node.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thanos-stack.fullname" . }}-graph-node
data:
{{- range $key, $value := .Values.graph_node.secret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end}}
{{- end}}