{{- if not .Values.createPvc}}
{{- if .Values.graph_node.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos-stack.fullname" . }}-ipfs
spec:
  selector:
    app: {{ include "thanos-stack.fullname" . }}-ipfs
  ports:
    - name: http
      port: 5001
      targetPort: 5001
{{- end}}
{{- end}}