{{- if .Values.l1_proxyd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos-stack.fullname" . }}-l1-proxyd
spec:
  selector:
    app: {{ include "thanos-stack.fullname" . }}-l1-proxyd
  ports:
    - name: http
      port: 8545
      protocol: TCP
      targetPort: 8080
    - name: ws
      port: 8546
      protocol: TCP
      targetPort: 8085
    - name: metric
      port: 9761
      protocol: TCP
      targetPort: 9761
    - name: pprof
      port: 6060
      targetPort: 6060
{{- end}}
