{{- if .Values.createPvc }}
{{- if .Values.op_challenger.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "thanos-stack.fullname" . }}-op-challenger
  labels:
    app: {{ include "thanos-stack.fullname" . }}-op-challenger
spec:
  capacity:
    storage: {{ default "100Gi" .Values.op_challenger.volume.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ default "efs-sc" .Values.op_challenger.volume.storage_class_name }}
  csi:
    driver: {{ default "efs.csi.aws.com" .Values.op_challenger.volume.csi.driver }} 
    volumeHandle: {{ .Values.op_challenger.volume.csi.volumeHandle }}
{{- end}}
{{- end}}