{{- if .Values.op_challenger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos-stack.fullname" . }}-op-challenger
spec:
  selector:
    matchLabels:
      app: {{ include "thanos-stack.fullname" . }}-op-challenger
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "thanos-stack.fullname" . }}-op-challenger
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/op-challenger-cm.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      initContainers:
        - name: wait-for-l2
          image: nicolaka/netshoot
          command: ["bash", "-c", "/wait-scripts/wait-for-l2.sh"]
          volumeMounts:
            - name: wait-scripts
              mountPath: /wait-scripts
          envFrom:
            - configMapRef:
                name: {{ include "thanos-stack.fullname" . }}-common
        - name: wait-for-rollup
          image: nicolaka/netshoot
          command: ["bash", "-c", "/wait-scripts/wait-for-rollup.sh"]
          volumeMounts:
            - name: wait-scripts
              mountPath: /wait-scripts
          envFrom:
            - configMapRef:
                name: {{ include "thanos-stack.fullname" . }}-common
      containers:
        - name: challenger
          image: {{ .Values.op_challenger.image }}
          imagePullPolicy: IfNotPresent
          command:
            ["/bin/sh", "/op-challenger-scripts/entrypoint-op-challenger.sh"]
          envFrom:
            - configMapRef:
                name: {{ include "thanos-stack.fullname" . }}-op-challenger
            - secretRef:
                name: {{ include "thanos-stack.fullname" . }}-secret
          volumeMounts:
            - name: challenger-data
              mountPath: /db
            - name: op-challenger-scripts
              mountPath: /op-challenger-scripts
      volumes:
        - name: wait-scripts
          configMap:
            name: {{ include "thanos-stack.fullname" . }}-wait-scripts
            defaultMode: 0777
        - name: op-challenger-scripts
          configMap:
            name: {{ include "thanos-stack.fullname" . }}-op-challenger-scripts
        - name: challenger-data
          persistentVolumeClaim:
            claimName: {{ include "thanos-stack.fullname" . }}-pvc-op-challenger
{{- end}}
