{{- if .Values.createPvc }}
{{- if .Values.op_challenger.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thanos-stack.fullname" . }}-op-challenger
spec:
  storageClassName: {{ default "efs-sc" .Values.op_challenger.volume.storage_class_name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ default "100Gi" .Values.op_challenger.volume.capacity }}
  selector:
    matchLabels:
      app: {{ include "thanos-stack.fullname" . }}-op-challenger
{{- end}}
{{- end}}