apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos-stack.fullname" . }}-op-geth
spec:
  selector:
    app: {{ include "thanos-stack.fullname" . }}-op-geth
  ports:
    - name: http
      port: 8545
      targetPort: 8545
    - name: ws
      port: 8546
      targetPort: 8546
    - name: auth
      port: 8551
      targetPort: 8551
    - name: p2p
      port: 30303
      targetPort: 30303
    - name: metric
      port: 6060
      targetPort: 6060
