{{- if .Values.enable_vpc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thanos-stack.fullname" . }}-op-node
spec:
  storageClassName: {{ default "efs-sc" .Values.op_node.volume.storage_class_name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ default "500Gi" .Values.op_node.volume.capacity }}
  selector:
    matchLabels:
      app: {{ include "thanos-stack.fullname" . }}-op-node
{{- end }}