apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos-stack.fullname" . }}-op-proposer
spec:
  selector:
    app: {{ include "thanos-stack.fullname" . }}-op-proposer
  ports:
    - name: http
      port: 8560
      protocol: TCP
      targetPort: 8560
    - name: metric
      port: 7300
      targetPort: 7300
