{{- if not .Values.createPvc }}
{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos-stack.fullname" . }}-redis
spec:
  selector:
    matchLabels:
      app: {{ include "thanos-stack.fullname" . }}-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "thanos-stack.fullname" . }}-redis
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/redis-cm.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: redis
          image: redis:alpine
          command: ['redis-server', '/redis-conf/redis.conf']
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: {{ default 0.5 .Values.redis.resources.cpu }}
              memory: {{ default "0.75Gi" .Values.redis.resources.memory }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /redis-conf
              name: redis-volume-config
      volumes:
        - name: redis-volume-config
          configMap:
            name: {{ include "thanos-stack.fullname" . }}-redis
{{- end}}
{{- end}}