apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "thanos-stack.fullname" . }}-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.thanos_stack_infra.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: {{ .Values.thanos_stack_infra.name }}
