{
 "title": "Bedrock OP Stack Dashboard",
 "description": "Bedrock OP Stack Application Dashboard",
 "tags": [
  "bedrock",
  "op-stack"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "L2 Block Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{job=~\"op-geth\"}"
    }
   ]
  },
  {
   "title": "L2 Chain Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_receipt{job=~\"op-geth\"}",
     "legendFormat": "transactions"
    },
    {
     "expr": "chain_head_block{job=~\"op-geth\"}",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "L1 RPC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-eth-node-synced\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OP Node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"op-node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OP Batcher",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"op-batcher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OP Geth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"op-geth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{job=~\"op-geth\"}"
    }
   ]
  },
  {
   "title": "OP Proposer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"op-proposer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active OP Stack Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"op-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}