apiVersion: v2
name: monitoring
description: A Helm chart for monitoring Thanos L2 Stack with Prometheus and Grafana
version: 0.1.0
type: application

dependencies:
  - name: kube-prometheus-stack
    version: "~45.0.0"
    repository: https://prometheus-community.github.io/helm-charts