{{- if .Values.l1_proxyd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos-stack.fullname" . }}-l1-proxyd
data:
  proxyd-config.toml: |
    ws_method_whitelist = [
      "debug_getBadBlocks",
      "debug_getRawBlock",
      "debug_getRawHeader",
      "debug_getRawReceipts",
      "debug_getRawTransaction",

      "eth_accounts",
      "eth_blockNumber",
      "eth_call",
      "eth_chainId",
      "eth_coinbase",
      "eth_createAccessList",
      "eth_estimateGas",
      "eth_feeHistory",
      "eth_gasPrice",
      "eth_getBalance",
      "eth_getBlockByHash",
      "eth_getBlockByNumber",
      "eth_getBlockReceipts",
      "eth_getBlockTransactionCountByHash",
      "eth_getBlockTransactionCountByNumber",
      "eth_getCode",
      "eth_getFilterChanges",
      "eth_getFilterLogs",
      "eth_getLogs",
      "eth_getProof",
      "eth_getStorageAt",
      "eth_getTransactionByBlockHashAndIndex",
      "eth_getTransactionByBlockNumberAndIndex",
      "eth_getTransactionByHash",
      "eth_getTransactionCount",
      "eth_getTransactionReceipt",
      "eth_getUncleCountByBlockHash",
      "eth_getUncleCountByBlockNumber",
      "eth_maxPriorityFeePerGas",
      "eth_newBlockFilter",
      "eth_newFilter",
      "eth_newPendingTransactionFilter",
      "eth_sendRawTransaction",
      "eth_sendTransaction",
      "eth_sign",
      "eth_signTransaction",
      "eth_subscribe",
      "eth_syncing",
      "eth_uninstallFilter",
      "eth_unsubscribe",
    ]
    ws_backend_group = "main"

    [server]
    rpc_host = "0.0.0.0"
    rpc_port = 8080
    ws_host = "0.0.0.0"
    ws_port = 8085
    max_body_size_bytes = 10485760
    max_concurrent_rpcs = 10000
    log_level = "info"
    enable_pprof = true

    [redis]
    url = {{ printf "redis://%s-redis:6379/0" (include "thanos-stack.fullname" .) | quote }}

    [cache]
    enabled = true

    [metrics]
    enabled = true
    host = "0.0.0.0"
    port = 9761

    [backend]
    response_timeout_seconds = 5
    max_response_size_bytes = 104857600
    max_retries = 3
    out_of_service_seconds = 20

    [backends]
{{- if .Values.l1_proxyd.backends }}
{{- range .Values.l1_proxyd.backends }}
    [backends.{{ .name }}]
    rpc_url = "{{ .rpc }}"
    ws_url = "{{ .ws }}"
    max_rps = 1000
    max_ws_conns = 0
    strip_trailing_xff = true
{{- if .consensus_receipts_target }}
    consensus_receipts_target = "{{ .consensus_receipts_target }}"
{{- end }}
{{ end }}
    [backend_groups]
    [backend_groups.main]
    backends = [
{{- range .Values.l1_proxyd.backends }}
{{- $backend := . }}
{{- range .groups }}
{{- if eq . "main" }}
      "{{ $backend.name }}",
{{- end }}
{{- end }}
{{- end }}
    ]

    [backend_groups.heavy_request]
    backends = [
{{- range .Values.l1_proxyd.backends }}
{{- $backend := . }}
{{- range .groups }}
{{- if eq . "heavy_request" }}
      "{{ $backend.name }}",
{{- end }}
{{- end }}
{{- end }}
    ]

    [backend_groups.alchemy]
    backends = [
{{- range .Values.l1_proxyd.backends }}
{{- $backend := . }}
{{- range .groups }}
{{- if eq . "alchemy" }}
      "{{ $backend.name }}",
{{- end }}
{{- end }}
{{- end }}
    ]
{{- end }}

    [rpc_method_mappings]
    debug_getBadBlocks = "main"
    debug_getRawBlock = "main"
    debug_getRawHeader = "main"
    debug_getRawReceipts = "main"
    debug_getRawTransaction = "main"
    eth_accounts = "main"
    eth_blockNumber = "main"
    eth_call = "main"
    eth_chainId = "main"
    eth_coinbase = "main"
    eth_createAccessList = "main"
    eth_estimateGas = "heavy_request"
    eth_feeHistory = "main"
    eth_gasPrice = "main"
    eth_getBalance = "main"
    eth_getBlockByHash = "main"
    eth_getBlockByNumber = "main"
    eth_getBlockReceipts = "heavy_request"
    eth_getBlockTransactionCountByHash = "main"
    eth_getBlockTransactionCountByNumber = "main"
    eth_getCode = "main"
    eth_getFilterChanges = "main"
    eth_getFilterLogs = "heavy_request"
    eth_getLogs = "heavy_request"
    eth_getProof = "main"
    eth_getStorageAt = "main"
    eth_getTransactionByBlockHashAndIndex = "main"
    eth_getTransactionByBlockNumberAndIndex = "main"
    eth_getTransactionByHash = "main"
    eth_getTransactionCount = "main"
    eth_getTransactionReceipt = "main"
    eth_getUncleCountByBlockHash = "main"
    eth_getUncleCountByBlockNumber = "main"
    eth_maxPriorityFeePerGas = "main"
    eth_newBlockFilter = "main"
    eth_newFilter = "main"
    eth_newPendingTransactionFilter = "main"
    eth_sendRawTransaction = "heavy_request"
    eth_sendTransaction = "main"
    eth_sign = "main"
    eth_signTransaction = "main"
    eth_subscribe = "main"
    eth_syncing = "main"
    eth_uninstallFilter = "main"
    eth_unsubscribe = "main"

    alchemy_getTransactionReceipts = "alchemy"
{{- end}}
