apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drb-vrf.fullname" . }}-secrets
  labels:
    {{- include "drb-vrf.labels" . | nindent 4 }}
type: Opaque
data:
  leader-peer-id-bytes: {{ .Values.leader.peerIDBytes }}
  {{- range $i, $r := .Values.regulars }}
  {{- $idx := add $i 1 }}
  regular-{{ $idx }}-peer-id-bytes: {{ $r.peerIDBytes }}
  {{- end }}
stringData:
  leader-private-key: {{ .Values.leader.privateKey | quote }}
  {{- range $i, $r := .Values.regulars }}
  {{- $idx := add $i 1 }}
  regular-{{ $idx }}-private-key: {{ $r.privateKey | quote }}
  {{- end }}
