{{- if .Values.blackboxExporter.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-blackbox-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yml: |
    modules:
      http_post_eth_node_synced_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ['HTTP/1.1', 'HTTP/2.0']
          valid_status_codes: []
          method: POST
          headers:
            content-type: application/json
          body: '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
          preferred_ip_protocol: 'ip4'
          ip_protocol_fallback: false
          fail_if_body_not_matches_regexp: ['false']
      http_post_eth_block_number_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ['HTTP/1.1', 'HTTP/2.0']
          valid_status_codes: []
          method: POST
          headers:
            content-type: application/json
          body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}'
          preferred_ip_protocol: 'ip4'
          ip_protocol_fallback: false
          fail_if_body_not_matches_regexp: ['0x']
      tcp_connect:
        prober: tcp
        timeout: 5s
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ['HTTP/1.1', 'HTTP/2.0']
          valid_status_codes: []
          method: GET
          preferred_ip_protocol: 'ip4'
          ip_protocol_fallback: false
      icmp:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: 'ip4'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-blackbox-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.24.0
          args:
            - '--config.file=/etc/blackbox_exporter/config.yml'
          ports:
            - containerPort: 9115
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox_exporter
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-blackbox-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-blackbox-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.blackboxExporter.service.type }}
  ports:
    - port: {{ .Values.blackboxExporter.service.port }}
      targetPort: 9115
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}