apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-blackbox-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: blackbox-exporter
data:
  blackbox.yml: |
    modules:
      http_post_eth_node_synced_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ['HTTP/1.1', 'HTTP/2.0']
          valid_status_codes: []
          method: POST
          headers:
            content-type: application/json
          body: '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
          preferred_ip_protocol: 'ip4'
          ip_protocol_fallback: false
          fail_if_body_not_matches_regexp: ['false']
      http_post_eth_block_number_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ['HTTP/1.1', 'HTTP/2.0']
          valid_status_codes: []
          method: POST
          headers:
            content-type: application/json
          body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}'
          preferred_ip_protocol: 'ip4'
          ip_protocol_fallback: false
          fail_if_body_not_matches_regexp: ['0x']
      tcp_connect:
        prober: tcp
        timeout: 5s
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ['HTTP/1.1', 'HTTP/2.0']
          valid_status_codes: []
          method: GET
          preferred_ip_protocol: 'ip4'
          ip_protocol_fallback: false
      icmp:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: 'ip4'