{{/* 
StorageClass and PersistentVolumes are handled externally:

1. EFS StorageClass (efs-sc) is created by terraform/kubernetes setup
2. PersistentVolumes are dynamically provisioned by the EFS CSI driver
3. kube-prometheus-stack creates PVCs automatically when storageSpec is configured

This template file is kept for reference but contains no active resources.
All storage provisioning is handled by:
- Terraform (creates EFS and StorageClass)
- kube-prometheus-stack subchart (creates PVCs)
- EFS CSI driver (provisions PVs dynamically)
*/}} 