{{- if .Values.kube-prometheus-stack.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-thanos-l2-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
    prometheus: {{ .Values.kube-prometheus-stack.fullnameOverride | default "monitoring" }}-prometheus
    role: alert-rules
spec:
  groups:
    - name: thanos-l2.rules
      interval: 30s
      rules:
        # OP Node 상태 체크
        - alert: OpNodeDown
          expr: up{job="op-node"} == 0
          for: 2m
          labels:
            severity: critical
            component: op-node
          annotations:
            summary: "OP Node is down"
            description: "OP Node has been down for more than 2 minutes."
            
        - alert: OpNodeHighMemoryUsage
          expr: (node_memory_MemTotal_bytes{job="op-node"} - node_memory_MemAvailable_bytes{job="op-node"}) / node_memory_MemTotal_bytes{job="op-node"} > 0.85
          for: 5m
          labels:
            severity: warning
            component: op-node
          annotations:
            summary: "OP Node high memory usage"
            description: "OP Node memory usage is above 85% for more than 5 minutes."
            
        # OP Batcher 상태 체크
        - alert: OpBatcherDown
          expr: up{job="op-batcher"} == 0
          for: 2m
          labels:
            severity: critical
            component: op-batcher
          annotations:
            summary: "OP Batcher is down"
            description: "OP Batcher has been down for more than 2 minutes."
            
        # OP Proposer 상태 체크
        - alert: OpProposerDown
          expr: up{job="op-proposer"} == 0
          for: 2m
          labels:
            severity: critical
            component: op-proposer
          annotations:
            summary: "OP Proposer is down"
            description: "OP Proposer has been down for more than 2 minutes."
            
        # OP Geth 상태 체크
        - alert: OpGethDown
          expr: up{job="op-geth"} == 0
          for: 2m
          labels:
            severity: critical
            component: op-geth
          annotations:
            summary: "OP Geth is down"
            description: "OP Geth has been down for more than 2 minutes."
            
        # Blackbox Exporter 체크
        - alert: EthNodeNotSynced
          expr: probe_success{job="blackbox-eth-node-synced"} == 0
          for: 5m
          labels:
            severity: warning
            component: ethereum-node
          annotations:
            summary: "Ethereum node is not synced"
            description: "Ethereum node sync check has been failing for more than 5 minutes."
            
        - alert: EthBlockNumberCheckFailed
          expr: probe_success{job="blackbox-eth-block-number"} == 0
          for: 5m
          labels:
            severity: warning
            component: ethereum-node
          annotations:
            summary: "Ethereum block number check failed"
            description: "Ethereum block number check has been failing for more than 5 minutes."
            
        # Blockscout 상태 체크
        - alert: BlockscoutDown
          expr: up{job="blockscout"} == 0
          for: 5m
          labels:
            severity: warning
            component: blockscout
          annotations:
            summary: "Blockscout is down"
            description: "Blockscout has been down for more than 5 minutes."
            
    - name: infrastructure.rules
      interval: 30s
      rules:
        # 일반적인 인프라 알림
        - alert: HighCpuUsage
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "CPU usage is above 80% for more than 5 minutes on {{ "{{ $labels.instance }}" }}."
            
        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage detected"
            description: "Memory usage is above 85% for more than 5 minutes on {{ "{{ $labels.instance }}" }}."
            
        - alert: DiskSpaceLow
          expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Low disk space"
            description: "Disk space is below 10% on {{ "{{ $labels.instance }}" }}."
{{- end }} 