{{- if .Values.kube-prometheus-stack.prometheus.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-op-stack-components
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      monitoring: "true"
      component: op-stack
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
    - port: debug-metrics
      path: /debug/metrics/prometheus
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
      - thanos

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-blockscout
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      monitoring: "true"
      app: blockscout
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 30s
  namespaceSelector:
    any: true

{{- end }} 