{{- if and .Values.thanosStack.releaseName .Values.thanosStack.namespace }}
# Universal ServiceMonitor for all OP Stack and Blockchain services
# Dynamically discovers services with proper labels and monitors multiple metric endpoints
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}-universal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.thanosStack.namespace }}
  selector:
    matchExpressions:
      # Match services with either app.kubernetes.io/name or app.kubernetes.io/instance labels
      - key: app.kubernetes.io/name
        operator: Exists
      - key: app.kubernetes.io/instance
        operator: Exists
  endpoints:
    # Standard metrics endpoint (most OP Stack components)
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: job
          regex: ".*-([^-]+)(?:-svc)?$"
          replacement: "${1}"
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service_name
    # Geth-style metrics endpoint
    - port: metrics
      path: /debug/metrics/prometheus
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: job
          regex: ".*(geth|l2geth).*"
          replacement: "geth"
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service_name
    # Blockscout metrics endpoint
    - port: http
      path: /metrics
      interval: 1m
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: job
          regex: ".*blockscout.*"
          replacement: "blockscout"
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service_name
    # Health check endpoint for frontend services
    - port: http
      path: /api/healthz
      interval: 1m
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: job
          regex: ".*(frontend|explorer).*"
          replacement: "frontend"
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service_name
{{- end }} 