# Values override for dynamic configuration based on global settings
# This ConfigMap contains the computed values for the monitoring stack

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-values-override
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  # Storage configuration
  storage-enabled: {{ .Values.global.storage.enabled | quote }}
  storage-class: {{ .Values.global.storage.storageClass | quote }}
  {{- if .Values.global.storage.efsFileSystemId }}
  efs-file-system-id: {{ .Values.global.storage.efsFileSystemId | quote }}
  {{- end }}
  force-efs: {{ .Values.global.storage.forceEFS | quote }}
  prometheus-size: {{ .Values.global.storage.prometheus.size | quote }}
  grafana-size: {{ .Values.global.storage.grafana.size | quote }}
  
  {{- if eq .Values.global.storage.storageClass "efs-sc" }}
  # EFS specific information
  efs-enabled: "true"
  storage-info: |
    EFS Storage Configuration:
    - StorageClass: {{ .Values.global.storage.storageClass }}
    - Access Mode: ReadWriteMany
    - Provisioner: efs.csi.aws.com
    {{- if .Values.global.storage.efsFileSystemId }}
    - File System ID: {{ .Values.global.storage.efsFileSystemId }}
    {{- else }}
    - File System ID: Auto-detected or created
    {{- end }}
    - Force EFS: {{ .Values.global.storage.forceEFS }}
  {{- end }}
  
  # Computed values for subchart configuration
  values-override.yaml: |
    # kube-prometheus-stack configuration
    kube-prometheus-stack:
      prometheus:
        prometheusSpec:
          # Storage configuration
          {{- if .Values.global.storage.enabled }}
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: {{ .Values.global.storage.storageClass | quote }}
                accessModes:
                  - "ReadWriteMany"  # EFS supports multi-pod access
                resources:
                  requests:
                    storage: {{ .Values.global.storage.prometheus.size | quote }}
          {{- end }}
          
          # Apply global security context
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          
          podSecurityContext:
            {{- toYaml .Values.global.podSecurityContext | nindent 12 }}
            
      # Grafana configuration
      grafana:
        # Persistence configuration
        {{- if .Values.global.storage.enabled }}
        persistence:
          enabled: true
          storageClassName: {{ .Values.global.storage.storageClass | quote }}
          size: {{ .Values.global.storage.grafana.size | quote }}
          accessModes:
            - ReadWriteMany  # EFS supports multi-pod access
        {{- else }}
        persistence:
          enabled: false  # Use emptyDir volumes
        {{- end }}
        
        # Apply global security context
        securityContext:
          {{- toYaml .Values.global.securityContext | nindent 10 }}
        
        podSecurityContext:
          {{- toYaml .Values.global.podSecurityContext | nindent 10 }}
          
      # Disable NodeExporter for Fargate compatibility
      nodeExporter:
        enabled: false

{{- if and .Values.thanosStack.releaseName .Values.thanosStack.namespace }}
---
# ConfigMap for Prometheus additional scrape configuration
# This is dynamically generated based on values.yaml scrapeTargets and global settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-scrape-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  # Additional scrape configs for Prometheus
  additional-scrape-configs.yaml: |
    {{- range $name, $config := .Values.scrapeTargets }}
    {{- if $config.enabled }}
    - job_name: {{ $name }}
      static_configs:
        - targets:
            - "{{ $.Values.thanosStack.releaseName }}-{{ $name }}:{{ $config.port }}"
      metrics_path: {{ $config.path }}
      scrape_interval: {{ $config.interval }}
    {{- end }}
    {{- end }}
    
    {{- if .Values.global.l1RpcUrl }}
    # Blackbox exporter health checks for L1 RPC
    - job_name: blackbox-eth-node-synced
      metrics_path: /probe
      params:
        module: [http_post_eth_node_synced_2xx]
      static_configs:
        - targets:
            - {{ .Values.global.l1RpcUrl | quote }}
      relabel_configs:
        - source_labels: [module]
          target_label: __param_module
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: target
        - target_label: __address__
          replacement: "{{ include "monitoring.fullname" . }}-prometheus-blackbox-exporter:9115"
          
    - job_name: blackbox-eth-block-number
      metrics_path: /probe
      params:
        module: [http_post_eth_block_number_2xx]
      static_configs:
        - targets:
            - {{ .Values.global.l1RpcUrl | quote }}
      relabel_configs:
        - source_labels: [module]
          target_label: __param_module
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: target
        - target_label: __address__
          replacement: "{{ include "monitoring.fullname" . }}-prometheus-blackbox-exporter:9115"
    {{- end }}
    
    # Custom additional scrape configurations (if any)
    {{- range .Values.additionalScrapeConfigs }}
    {{ . | toYaml | nindent 4 }}
    {{- end }}

{{- end }} 