apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "op-bridge.fullname" . }}
data:
  .env: |-
{{- range $key, $value := .Values.op_bridge.env }}
    NEXT_PUBLIC_{{ $key | upper }}: {{ $value | quote }}
{{- end }}
