{{- if .Values.op_bridge.ingress.enabled }}
{{- $fullName := include "op-bridge.fullname" . -}}
{{- if and .Values.op_bridge.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    app: {{ $fullName }}
  {{- with .Values.op_bridge.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.op_bridge.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.op_bridge.ingress.className }}
  {{- end }}
  {{- if .Values.op_bridge.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.op_bridge.ingress.hostname | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.op_bridge.ingress.hostname | quote }}
      http:
        paths:
          {{- range .Values.op_bridge.ingress.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: 3000
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: 3000
              {{- end }}
          {{- end }}
{{- end}}
