apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-bridge.fullname" . }}
spec:
  selector:
    app: {{ include "op-bridge.fullname" . }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
